import { StructuresInterface } from 'src/Mongo/Interface/structures.interface';

export const DengueStructure: StructuresInterface = {
  name: 'Dengue',
  states: [],
  lengthParams: 41,
  type_parameters: {
    '0-AMB-00-IndexQuadras': [],
    '0-AMB-01-IndexVizinhancas': [],
    '0-AMB-02-VetorVizinhancas': [],
    '0-AMB-03-IndexPosicoes': [],
    '0-AMB-04-VetorPosicoes': [],
    '0-AMB-05-IndexPosicoesRegioes': [],
    '0-AMB-06-IndexFronteiras': [],
    '0-AMB-07-VetorFronteiras': [],
    '0-AMB-08-IndexEsquinas': [],
    '0-AMB-09-VetorEsquinas': [],
    '0-AMB-10-IndexCentrosEsquinas': [],
    '0-AMB-11-VetorCentrosEsquinas': [],
    '1-MOV-00-IndexRotas': [],
    '1-MOV-01-VetorRotas': [],
    '1-MOV-02-IndexTrajetos': [],
    '1-MOV-03-IndexPeriodos': [],
    '1-MOV-04-VetorPeriodos': [],
    '1-MOV-05-IndexTrajetosFaixaEtaria': [],
    '2-CON-00-QuadrasVacinacao': [],
    '2-CON-01-FaixasEtariasVacinacao': [],
    '2-CON-02-CiclosVacinacao': [],
    '2-CON-03-QuadrasControleBio': [],
    '2-CON-04-QuadrasControleAmb': [],
    '2-CON-05-PontosEstrategicos': [],
    '2-CON-06-IndexFocos': [],
    '2-CON-07-VetorFocos': [],
    '2-CON-08-ControlePorQuadra': [],
    '2-CON-09-VetorComplemento': [],
    '2-CON-10-VetorCasos': [],
    '2-CON-11-InfoControles': [],
    '2-CON-12-IndexContrPontos': [],
    '2-CON-13-ContrPontos': [],
    '2-CON-14-IndexPontosRaios': [],
    '2-CON-15-PontosRaios': [],
    '2-CON-16-HumanosVacinados': [],
    '3-CLI': [],
    DistribuicaoHumanos: [],
    DistribuicaoMosquitos: [],
    focos: [],
    lotes: [],
    pes: [],
  },
  defaultSearch: ['aa', 'aaa'],
  outputFolder: 'dengue/',
};

//APENAS PARA TESTE
export const TesteStructure: StructuresInterface = {
  name: 'TESTE123',
  states: [],
  lengthParams: 1,
  type_parameters: {
    a: [],
  },
  defaultSearch: ['aa', 'aaa'],
  outputFolder: 'teste_files/',
};
